version: 0.1.{build}

stack: node 9

#branches:
#  only:
#    - master
#    - dev

image:
  - Visual Studio 2017
  - ubuntu

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input
  - node --version

install:
  - ps: Install-Product node 9 x64
  - git reset --hard HEAD
  - yarn

build_script:
  - yarn build

test: off
